page_list:
  path: /page
  defaults: { _controller: PageBundle:Page:list }

page_add:
  path: /page/add
  defaults: { _controller: PageBundle:Page:add }

page_view:
  path: /page/{id}
  defaults: { _controller: PageBundle:Page:view }

#page_comments:
#  path: /page/{id}/comments



#page_edit:
#  path: /page/{id}/edit
#
#page_delete:
#  path: /page/{id}/delete
